# Generated by Django 5.2.8 on 2026-01-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('nacional', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='TipoAco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espessura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liga_metalica', models.CharField(max_length=45)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aço',
                'verbose_name_plural': 'Tipos de Aço',
            },
        ),
        migrations.CreateModel(
            name='TipoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_controle', models.CharField(max_length=45, verbose_name='Nº do MTC / Certificado')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='mtcs/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtcs', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'MTC',
                'verbose_name_plural': 'MTCs',
            },
        ),
        migrations.CreateModel(
            name='Bobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida', models.CharField(max_length=45, unique=True)),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bobinas', to='estoque.mtc')),
                ('tipo_aco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipoaco')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_consumo', models.DateTimeField(auto_now_add=True)),
                ('bobina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='estoque.bobina')),
                ('tipo_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipoconsumo')),
            ],
        ),
    ]
