# Generated by Django 5.2.8 on 2026-01-06 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtc',
            options={},
        ),
        migrations.AddField(
            model_name='bobina',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bobina',
            name='mtc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.mtc'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='bobina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.bobina'),
        ),
        migrations.AlterField(
            model_name='mtc',
            name='num_controle',
            field=models.CharField(max_length=45, verbose_name='Nº do MTC'),
        ),
    ]
