# Generated by Django 5.2.8 on 2026-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_mtc_options_bobina_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações / OP'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
