# Generated by Django 5.2.8 on 2026-03-15 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_bobina_usuario_cadastro_mtc_usuario_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtc',
            name='data_emissao',
        ),
        migrations.AddField(
            model_name='bobina',
            name='alongamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alongamento (%)'),
        ),
        migrations.AddField(
            model_name='bobina',
            name='escoamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Escoamento'),
        ),
        migrations.AddField(
            model_name='bobina',
            name='resistencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resistência'),
        ),
        migrations.AddField(
            model_name='mtc',
            name='data_recebimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Recebimento'),
            preserve_default=False,
        ),
    ]
