# Generated by Django 5.2.8 on 2026-03-15 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_mtc_data_emissao_bobina_alongamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtc',
            name='num_controle',
            field=models.CharField(max_length=45, verbose_name='Identificação (NF / Container)'),
        ),
        migrations.AddConstraint(
            model_name='mtc',
            constraint=models.UniqueConstraint(fields=('num_controle', 'data_recebimento'), name='unique_mtc_por_dia'),
        ),
    ]
