# Generated by Django 6.0 on 2026-05-17 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_mtc_num_controle_mtc_unique_mtc_por_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDivergenciaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mtc', models.CharField(max_length=100, verbose_name='Número do MTC')),
                ('detalhes_erro', models.TextField(verbose_name='O que a IA errou e como deveria ser?')),
                ('data_reporte', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Análise'), ('RESOLVIDO', 'Ajustado no Prompt / Resolvido'), ('DESCARTADO', 'Erro do Operador (Ignorar)')], default='PENDENTE', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
